### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by adamskiij99** [adamskiij99/BM-convex-hull#1]
- [x] Include correlation parameter
- [x] Add 3-dimensional version
- [x] Give option to view the evolution of the process and running hull over time
- [ ] Add auxilliary information/statistics/visualisations to illustrate results about the hull

**Comment by adamskiij99** [comment]
auxilliary info ongoing
